FROM golang:1.22

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/engine/reference/builder/#copy
COPY /app/main.go ./

# Build
# Specify an executable name for the output, e.g., "myapp"
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/mywebserver

EXPOSE 9000

# Run the specified executable
CMD ["/app/mywebserver"]


# How to run:
# cd mercari/mercari-build-training/go
# docker build -t build2024/app:latest .
# docker run -p 9000:9000 build2024/app:latest
# Refer: https://docs.docker.com/language/golang/build-images/